#install:
#
#  # Install a custom version of shellcheck instead of Travis CI's default
#  - scversion="stable" # or "v0.4.7", or "latest"
#  - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
#  - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
#  - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
#  - shellcheck --version

script:
  - shellcheck $(grep -rl '"^#!/bin/sh\|^#!/bin/bash\|^#!/usr/bin/env bash' ./ | grep -v ".git\|travis.yml")
